### ISSUE TITLE
support for OpsGenie REST API v2

### ISSUE THREAD

**Issue by sun-pgdx** [opsgenie/opsgenie-python-sdk#11]
Thank you for opsgenie-python-sdk.

Are there plans to support the new version of the OpsGenie REST API?

Note that:
- the API key is now supposed to be specified in the HTTP request header.
- the recipient list changed to responders (payload datastructure change too).
 
Also, does the comment at line 90 in the create_alert() method in the opsgenie/alert/service.py suggest that the REST end-point may be hard-coded (immutable)?
<pre>
https://www.opsgenie.com/docs/web-api/alert-api#createAlertRequest
</pre>

The REST API 2 is:
<pre>
https://api.opsgenie.com/v2/alerts
</pre>

**Comment by christophetd** [comment]
+1, any update on that?

**Comment by AntoonNaegels** [comment]
+1, It wasn't documented that another API had to be used. Fix this SOON please.

**Comment by davidkarlsen** [comment]
Same for the java sdk - just suddenly stopped working, no new version published in central: http://repo1.maven.org/maven2/com/opsgenie/integration/

**Comment by muhammadhamzakhan** [comment]
We have released the new version of the Python SDK in the the same repo. You can access the documentation at https://docs.opsgenie.com/docs/opsgenie-python-api-v2-1
