### ISSUE TITLE
Support for Incident API

### ISSUE THREAD

**Issue by davidban77** [opsgenie/opsgenie-python-sdk#12]
Hello,

Currently there is not support for the [Incident API](https://docs.opsgenie.com/docs/incident-api).

Would love to have this functionality for Incidents retrieval and manipulation.

**Comment by muhammadhamzakhan** [comment]
Hi, 

We have updated our SDK and have added support for the Incident API as well. Please feel free to check it out and perhaps provide some feedback about it as well.

**Comment by davidban77** [comment]
Tested it and love  it! great work on the documentation, makes the creation of methods and functions a lot easier and intuitive, making the application we are using with it more streamlined and easier to understand and follow.
