### ISSUE TITLE
The default endpoint does not work for the EU

### ISSUE THREAD

**Issue by hakanisaksson** [opsgenie/opsgenie-python-sdk#13]
Opsgenie users within the EU have to talk to https://api.eu.opsgenie.com/ for the API to work, and there is no information about that or any documented way to change the api endpoint. 

A way to configure it that works for me is adding:
configuration.host = 'https://api.eu.opsgenie.com'
in the same place where the api-key is configured.

It should be documented how to change the endpoint config, preferably with code examples.

**Comment by muhammadhamzakhan** [comment]
We have released the new version of the Python SDK, with code examples for Alert, Incident, Heartbeat, and Account domains, in the the same repo. You can access the documentation at https://docs.opsgenie.com/docs/opsgenie-python-api-v2-1

The specific documentation about all possible configurations, including the host, can be accessed at https://docs.opsgenie.com/docs/opsgenie-python-sdk-configurations
