### ISSUE TITLE
ModuleNotFound

### ISSUE THREAD

**Issue by Mexflubber** [opsgenie/opsgenie-python-sdk#18]
After installing opsgenie_sdk in python3 via pip3 install opsgenie_sdk I get the following error

   import opsgenie_sdk
ModuleNotFoundError: No module named 'opsgenie_sdk'

**Comment by jkinred** [comment]
It looks like all the published documentation is referring to a new version of the API which is marked on PyPI as a pre-release. We need to install with the `--pre` flag:

    pip install --pre opsgenie_sdk

Very confusing.

**Comment by muhammadhamzakhan** [comment]
The SDK was in beta at that time, but it has been officially released on PyPi since then
