### ISSUE TITLE
Inconsistency in sort field values for Incident API and Alert API

### ISSUE THREAD

**Issue by davidban77** [opsgenie/opsgenie-python-sdk#24]
Hi,

I have stumbled with this error:

```python
HTTP response body: {"message": "Invalid sort field.", "took": 0.001, "requestId": "xzxzxzxzxz", "url": "https://api.opsgenie.com/v1/incidents/"}
```

This happens when trying to use the `list_incidents` method on the `IncidentApi` with:

`sort="created_at"`

It works when is set as camel case `createdAt`, but is not consistent with the `AlertApi`

**Comment by muhammadhamzakhan** [comment]
Hello, 

As mentioned in the documentation of the [AlertApi](https://docs.opsgenie.com/docs/alert-api#section-list-alerts) and [IncidentApi](https://docs.opsgenie.com/docs/incident-api#section-list-incidents), both of them accept `createdAt` value for the sort query parameter, making them consistent with each other. 

However, the alertApi does indeed also accept 'created_at' along with 'createdAt'. And making the alertApi stop accepting 'created_at' might introduce breaking changes for some customers and will hence not be introduced for now. We can consider removing it in the next major release of the SDK though.

**Comment by davidban77** [comment]
Got it, I thought since is the python SDK the translation was made for almost all variables and method from camel case to snake case, hence I thought the "correct way" was to use `created_at`.

Thanks for the clarification!
