### ISSUE TITLE
cannot list alert 

### ISSUE THREAD

**Issue by debu99** [opsgenie/opsgenie-python-sdk#34]
Return below error depends on the query 
ValueError: Invalid value for `type` (schedule), must be one of ['user', 'team']
ValueError: Invalid value for `type` (escalation), must be one of ['user', 'team']

**Comment by muhammadhamzakhan** [comment]
Hi, thanks for pointing it out. The problem will be fixed when https://github.com/opsgenie/opsgenie-python-sdk/pull/35 is merged
