### ISSUE TITLE
client.configuration.apikey AttributeError

### ISSUE THREAD

**Issue by eguven** [opsgenie/opsgenie-python-sdk#4]
I was using a long lived object (opsgenie client) to send alerts and every once in a while I get this exception even though the same object has been working fine for a while:

      File ".../mypackage/myfile.py", line 152, in _create_alert
        response = self.client.alert.create_alert(request)
      File "/usr/local/lib/python3.6/site-packages/opsgenie/service.py", line 149, in request_call
        params = generate_params(self.configuration.apikey, request)
    AttributeError: 'Configuration' object has no attribute 'apikey'

Obviously I create it with a legit apikey and even send alerts before.

    self.client = OpsGenie(Configuration(apikey=my_apikey))

**Comment by eguven** [comment]
Ok, so it's caused by the recent renaming of `apikey` -> `api_key` and forgotten use case. Found it using this compare: https://github.com/opsgenie/opsgenie-python-sdk/compare/b8e949a...fa743f6#diff-6abe80eaaa1272a17f998459154c08d6

Unfortunately this line is still using `apikey` which no longer exists: https://github.com/opsgenie/opsgenie-python-sdk/blob/9cd41213b73de6a830ff19143ed727cf52cfcf6e/opsgenie/service.py#L149

Since all my alerting was broken, as a quick workaround I did

    og.client.configuration.apikey = og.client.configuration.api_key

**Comment by alpgurtan** [comment]
Sorry about the late answer but seems like you already found the problem. I will send the fix in 24 hour with correcting documentation (**Thanks for warning!**). Also, we are open to contributions and pull requests (if you want) :)

As for the release/deprecation problem, we are continuing Python SDK with Beta releases and discussing Swagger for the future implementations. If you have any opinion on it, we will happy to hear it in our community page. You can use this [category](https://community.opsgenie.com/c/integrations/sdks) for feedback/requests and there is already ongoing request in this [topic](https://community.opsgenie.com/t/openapi-swagger-specification/381) about Swagger
