### ISSUE TITLE
Add all APIs to the SDK

### ISSUE THREAD

**Issue by iksaif** [opsgenie/opsgenie-python-sdk#5]
Could you also generate (with swagger) the stubs for the other APIs ? (Calendar, Teams, etc.. ?)
Thanks !

**Comment by iksaif** [comment]
Thanks for the links :)

**Comment by alpgurtan** [comment]
Hi again!

As a future reference, We decided to introduce all domains via Swagger and also share our yaml in github. I'm not sure about Java but seems like [swagger-codegen](https://github.com/swagger-api/swagger-codegen) could generate basic Python SDK without too many bugs :) We can use that for fully Swagger generated SDK.

I want to update this issue with good news, thanks for your patience :)

**Comment by iksaif** [comment]
:+1:

**Comment by iksaif** [comment]
See https://github.com/opsgenie/opsgenie-python-sdk/issues/9

**Comment by muhammadhamzakhan** [comment]
We have released the new version of the Python SDK, with code examples for Alert, Incident, Heartbeat, and Account domains, in the the same repo. You can access the documentation at https://docs.opsgenie.com/docs/opsgenie-python-api-v2-1 

You may choose to manually generate the remaining domains by using our extended [OpenAPI Generator](https://github.com/opsgenie/opsgenie-python-openapi-generator) in combination with the [Opsgenie OpenAPI Specification](https://github.com/opsgenie/opsgenie-oas).
