### ISSUE TITLE
Regenerate swagger api with new oas

### ISSUE THREAD

**Issue by solarmicrobe** [opsgenie/opsgenie-python-sdk#9]
It looks like opsgenie-oas has been updated with heartbeat api endpoints.  Can we get this project updated to include those?

I tried to use the swagger-codegen to recreate the python sdk but couldn't quite figure out the commands needed to get it done. (an example command would also work for me).

**Comment by iksaif** [comment]
:+1:

**Comment by iksaif** [comment]
https://github.com/opsgenie/opsgenie-oas/pull/35

**Comment by iksaif** [comment]
As a temporary workaround, you can try https://github.com/criteo-forks/opsgenie-python-sdk (or pip install opsgenie_swagger) which contains all the newly generated code. We will deprecate this package if opsgenie-python-sdk gets updated.

**Comment by muhammadhamzakhan** [comment]
We have released the new version of the Python SDK, with code examples for Alert, Incident, Heartbeat, and Account domains, in the the same repo. You can access the documentation at https://docs.opsgenie.com/docs/opsgenie-python-api-v2-1 

You may choose to manually generate the remaining domains by using our extended [OpenAPI Generator](https://github.com/opsgenie/opsgenie-python-openapi-generator) in combination with the [Opsgenie OpenAPI Specification](https://github.com/opsgenie/opsgenie-oas).
